### ISSUE TITLE
Allow adhoc mutations to be invoked

### ISSUE THREAD

**Issue by wilkerlucio** [fulcrologic/fulcro-inspect#28]
Add a text field on the transactions tab, from where the user could invoke mutations.

**Comment by awkay** [comment]
Actually, I'd like to be able to do this in the query tab, and it does seem to send it correctly, but when I run a mutation like this (for which I have a pathom setup on the server):

```
[{(demo/twiddle {:demo/id 1}) [:demo/today]}]
```

It runs fine on the server, returns the correct response, but then the pathom stuff embedded in inspect puts this in the right-hand pane:

```
{demo/twiddle
 {:com.wsscode.pathom.core/reader-error
  "Mutation not found - {:mutation demo/twiddle}"}}
```

which I assume happens because the result is going through something in inspect that is using pathom?  This is definitely not what the server returned.

**Comment by wilkerlucio** [comment]
@awkay I think query tab is not that, the query tab is to run queries against a remote, so they are not part of the UI transactions and I think this is a desirable feature (keep query constrained to remote). That's why I think it should be on the transactions tab, so it runs as transactions, makes sense?

**Comment by awkay** [comment]
I don't know.  Mutations can be in joins, and always can have return values. So, supporting full EQL in the query tab makes sense to me.  Database interfaces to SQL don't make you go "elsewhere" to run DDL vs DQL.

**Comment by awkay** [comment]
Since neither of us plans to do anything about this in the immediate future, I'm closing this. A PR adding support will suffice to resurface the issue.
