### ISSUE TITLE
Assertion error on startup (minimal case to follow)

### ISSUE THREAD

**Issue by levitanong** [fulcrologic/fulcro-inspect#31]
In the project I'm working on, about 18 copies of this error appears. I currently suspect it's related to the number of mutations I've registered. I will investigate soon. As the title says, minimal case to follow.

```
[fulcro.client.impl.application] Mutation  fulcro.inspect.ui.transactions/add-tx  failed with exception Error: Assert failed: Path [:fulcro.inspect.ui.transactions/tx-list-id [:fulcro.inspect.core/app-id some-app.ui.root/Root] :fulcro.inspect.ui.transactions/tx-list] for append must target an app-state vector.
(vector? (get-in state data-path))
```

**Comment by wilkerlucio** [comment]
I need some code example; if you can send a repo that I can clone and see the error on my end would be great!

**Comment by levitanong** [comment]
It's currently 3:30 am in my timezone, so I'll do that during the day. :) It will take time, because this is a relatively big project.

**Comment by wilkerlucio** [comment]
No hurry ;)

**Comment by levitanong** [comment]
I'm still in the process of making a minimal case, but it's clear to me now that it has something to do with ui routing. The number of copies of the error directly correlates to how many routes (recursively) there are as defined by `r/defrouter`.

**Comment by wilkerlucio** [comment]
@levitanong hello, I just pushed `2.0.0-alpha7-SNAPSHOT`, the problem was that Fulcro is calling `merge` before the inspector has a chance to start. To fix it, now when inspect is ready (after app initialization is called) I add a flag to your app state to signal that. And then any calls to `inspect-tx` before that flag is set are going to be ignored. I hope this fixes the issue once for all. Please let me know it works properly with the new version. Thanks.

**Comment by levitanong** [comment]
Works! Thanks @wilkerlucio!
