### ISSUE TITLE
Chrome plugin sucks CPU

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro-inspect#40]
Not sure what happened, but when using the chrome plugin it started sucking CPU like mad. The older version of inspect didn't do this. The main note is the the app I'm running has a very high transaction rate during page load (perhaps 50+ transact! calls on page load).

I had to back out to an earlier version for normal work because it added too much overhead. 2.1.0 is fine.

**Comment by wilkerlucio** [comment]
@awkay Please try `[fulcrologic/fulcro-inspect "2.2.0-beta-1"]` with Chrome plugin version `0.0.2`, I did major changes on the transaction communication, now it doesn't have to convert any DB parts anymore. Before it was probably worse than we imagined, because it had 4 versions of the db to be encoded at least, now it's down to zero. Please let me know if now it's suitable for the app you were working.

**Comment by wilkerlucio** [comment]
@awkay do you think we can close this after tx db hash optimization?

**Comment by awkay** [comment]
I no longer see CPU problems.
