### ISSUE TITLE
Electron client

### ISSUE THREAD

**Issue by wilkerlucio** [fulcrologic/fulcro-inspect#43]

**Comment by afhammad** [comment]
+10

**Comment by mdhaney** [comment]
It appears this feature has stalled.  Working with React Native, this could be really useful.  I was wondering, does it need to be an Electron app?  Could it just be a web app that connects to the web socket? (We could have shadow-cljs serve up the page, like it does for workspaces, etc.).   If you can point me in the right direction to get started, I can take a stab at this since I could really use the feature myself.

Another possible option (for React Native) - I can make RN run the Javascript on Chrome (using Expo at least, not sure about plain RN).  I already tried and Fulcro inspect doesn’t detect the app - probably because it’s running as a web worker.  So if there’s a simple fix to make the current plugin aware of web workers, that would work too.  Whichever is easier, let me know and I’ll take a stab at it.

**Comment by awkay** [comment]
Yeah, none of the maintainers have a personal need, so help would be appreciated.

The basic functionality needs to communicate messages to/from the actual client to/from the inspect tool.  Of course the client is running in (in your case) a React Native env. There is no way (I know of) to create a websocket *server* on a normal browser...but Electron app could do it, which is why we've done some probing into creating it that way.

Inspect itself (what you see in the Chrome tool tab) is just a Fulcro application. All that needs to happen is for there to be a com link.

I can walk you through the basics if you want to PM me.

**Comment by awkay** [comment]
I've done an initial version of this, with Linux/Mac binaries. See Releases on this Repo.
