### ISSUE TITLE
Not working in an iframe

### ISSUE THREAD

**Issue by fatihict** [fulcrologic/fulcro-inspect#50]
The current version of fulcro-inspect `2.2.0-beta8` is not connecting to my app which runs in an iframe.

**Comment by wilkerlucio** [comment]
Yeah, currently the new versions are only compatible with the chrome extension version, getting it working again on the iframe is a bit complicated due to some heavier usages of JS libraries. I think the Electron version is easier to get going at this point then the iFrame, but I don't see that been worked out soon by me, but I would be happy to accept a PR for it, most of it should just work like the chrome ext, the parts that need change are just to setup the communication between electron and the browser via a websocket, when the messaging is ready the plug of it should be easy.
